name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: |
          npm run build:content
          npm run build
          touch out/.nojekyll   # 避免 GitHub Pages 忽略 _ 开头的文件

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
